#cloud-config
hostname: $[hostname}
fqdn: $[hostname}.local

users:
  - name: tester
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh-authorized-keys:
      - "${ssh_public_key}"

# Update and install basic packages
package_update: true
package_upgrade: true

packages:
  - curl
  - git
  - htop
  - openssh-server
  - net-tools
  - vim
  - qemu-guest-agent

# Enable qemu-guest-agent
runcmd:
  - systemctl enable --now qemu-guest-agent
  - systemctl restart qemu-guest-agent

# Resize root filesystem (usually automatic, but safe to force)
growpart:
  mode: auto
  devices: ['/']
  ignore_fail: true

power_state:
  delay: 0
  mode: poweroff
  message: "First boot completed"
  timeout: 30
